In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [6]:
data = pd.read_csv('data/training_set_features.csv')
labels = pd.read_csv('data/training_set_labels.csv')

In [4]:
data.describe()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,household_adults,household_children
count,26707.00000,26615.00000,26591.00000,26636.00000,26499.00000,26688.00000,26665.00000,26620.00000,26625.00000,26579.00000,24547.00000,24547.00000,25736.00000,25887.00000,25903.00000,14433.00000,26316.00000,26319.00000,26312.00000,26245.00000,26193.00000,26170.00000,26458.00000,26458.00000
mean,13353.00000,1.61849,1.26253,0.04884,0.72561,0.06898,0.82561,0.35864,0.33731,0.67726,0.22031,0.32973,0.28326,0.08259,0.11192,0.87972,3.85062,2.34257,2.35767,4.02599,2.71916,2.11811,0.88650,0.53458
std,7709.79116,0.91031,0.61815,0.21555,0.44621,0.25343,0.37945,0.47961,0.47280,0.46753,0.41447,0.47013,0.45059,0.27527,0.31527,0.32530,1.00744,1.28554,1.36277,1.08656,1.38506,1.33295,0.75342,0.92817
min,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000
25%,6676.50000,1.00000,1.00000,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,3.00000,1.00000,1.00000,4.00000,2.00000,1.00000,0.00000,0.00000
50%,13353.00000,2.00000,1.00000,0.00000,1.00000,0.00000,1.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,4.00000,2.00000,2.00000,4.00000,2.00000,2.00000,1.00000,0.00000
75%,20029.50000,2.00000,2.00000,0.00000,1.00000,0.00000,1.00000,1.00000,1.00000,1.00000,0.00000,1.00000,1.00000,0.00000,0.00000,1.00000,5.00000,4.00000,4.00000,5.00000,4.00000,4.00000,1.00000,1.00000
max,26706.00000,3.00000,2.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,5.00000,5.00000,5.00000,5.00000,5.00000,5.00000,3.00000,3.00000

In [8]:
data.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,3.00000,1.00000,2.00000,2.00000,1.00000,2.00000,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.00000,0.00000,NaN,NaN
1,1,3.00000,2.00000,0.00000,1.00000,0.00000,1.00000,0.00000,1.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,5.00000,4.00000,4.00000,4.00000,2.00000,4.00000,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.00000,0.00000,pxcmvdjn,xgwztkwe
2,2,1.00000,1.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,nan,nan,1.00000,0.00000,0.00000,nan,3.00000,1.00000,1.00000,4.00000,1.00000,2.00000,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.00000,0.00000,rucpziij,xtkaffoo
3,3,1.00000,1.00000,0.00000,1.00000,0.00000,1.00000,1.00000,0.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,nan,3.00000,3.00000,5.00000,5.00000,4.00000,1.00000,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.00000,0.00000,NaN,NaN
4,4,2.00000,1.00000,0.00000,1.00000,0.00000,1.00000,1.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,nan,3.00000,3.00000,2.00000,3.00000,1.00000,4.00000,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.00000,0.00000,wxleyezf,emcorrxb

In [7]:
labels.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [9]:
labels.describe()

       respondent_id  h1n1_vaccine  seasonal_vaccine
count    26707.00000   26707.00000       26707.00000
mean     13353.00000       0.21245           0.46561
std       7709.79116       0.40905           0.49883
min          0.00000       0.00000           0.00000
25%       6676.50000       0.00000           0.00000
50%      13353.00000       0.00000           0.00000
75%      20029.50000       0.00000           1.00000
max      26706.00000       1.00000           1.00000

In [16]:
print(labels['h1n1_vaccine'].value_counts())
print(labels['seasonal_vaccine'].value_counts())

0    21033
1     5674
Name: h1n1_vaccine, dtype: int64
0    14272
1    12435
Name: seasonal_vaccine, dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 36 columns):
respondent_id                  26707 non-null int64
h1n1_concern                   26615 non-null float64
h1n1_knowledge                 26591 non-null float64
behavioral_antiviral_meds      26636 non-null float64
behavioral_avoidance           26499 non-null float64
behavioral_face_mask           26688 non-null float64
behavioral_wash_hands          26665 non-null float64
behavioral_large_gatherings    26620 non-null float64
behavioral_outside_home        26625 non-null float64
behavioral_touch_face          26579 non-null float64
doctor_recc_h1n1               24547 non-null float64
doctor_recc_seasonal           24547 non-null float64
chronic_med_condition          25736 non-null float64
child_under_6_months           25887 non-null float64
health_worker                  25903 non-null float64
health_insurance               14433 non-null float64
opinion_h1n1_vacc_effective    26316 non-null float64
opinion_h1n1_risk              26319 non-null float64
opinion_h1n1_sick_from_vacc    26312 non-null float64
opinion_seas_vacc_effective    26245 non-null float64
opinion_seas_risk              26193 non-null float64
opinion_seas_sick_from_vacc    26170 non-null float64
age_group                      26707 non-null object
education                      25300 non-null object
race                           26707 non-null object
sex                            26707 non-null object
income_poverty                 22284 non-null object
marital_status                 25299 non-null object
rent_or_own                    24665 non-null object
employment_status              25244 non-null object
hhs_geo_region                 26707 non-null object
census_msa                     26707 non-null object
household_adults               26458 non-null float64
household_children             26458 non-null float64
employment_industry            13377 non-null object
employment_occupation          13237 non-null object
dtypes: float64(23), int64(1), object(12)
memory usage: 7.3+ MB

In [19]:
data.isna().sum()

respondent_id                      0
h1n1_concern                      92
h1n1_knowledge                   116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_h1n1                2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_h1n1_vacc_effective      391
opinion_h1n1_risk                388
opinion_h1n1_sick_from_vacc      395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                 249
household_children               249
employment_industry            13330
employment_occupation          13470
dtype: int64

In [23]:
for c in data.columns:
    print(data[c].value_counts())

2047     1
7657     1
3371     1
13612    1
15661    1
        ..
12979    1
2740     1
693      1
6838     1
0        1
Name: respondent_id, Length: 26707, dtype: int64
2.00000    10575
1.00000     8153
3.00000     4591
0.00000     3296
Name: h1n1_concern, dtype: int64
1.00000    14598
2.00000     9487
0.00000     2506
Name: h1n1_knowledge, dtype: int64
0.00000    25335
1.00000     1301
Name: behavioral_antiviral_meds, dtype: int64
1.00000    19228
0.00000     7271
Name: behavioral_avoidance, dtype: int64
0.00000    24847
1.00000     1841
Name: behavioral_face_mask, dtype: int64
1.00000    22015
0.00000     4650
Name: behavioral_wash_hands, dtype: int64
0.00000    17073
1.00000     9547
Name: behavioral_large_gatherings, dtype: int64
0.00000    17644
1.00000     8981
Name: behavioral_outside_home, dtype: int64
1.00000    18001
0.00000     8578
Name: behavioral_touch_face, dtype: int64
0.00000    19139
1.00000     5408
Name: doctor_recc_h1n1, dtype: int64
0.00000    16453
1.00000     8094
Name: doctor_recc_seasonal, dtype: int64
0.00000    18446
1.00000     7290
Name: chronic_med_condition, dtype: int64
0.00000    23749
1.00000     2138
Name: child_under_6_months, dtype: int64
0.00000    23004
1.00000     2899
Name: health_worker, dtype: int64
1.00000    12697
0.00000     1736
Name: health_insurance, dtype: int64
4.00000    11683
5.00000     7166
3.00000     4723
2.00000     1858
1.00000      886
Name: opinion_h1n1_vacc_effective, dtype: int64
2.00000    9919
1.00000    8139
4.00000    5394
5.00000    1750
3.00000    1117
Name: opinion_h1n1_risk, dtype: int64
2.00000    9129
1.00000    8998
4.00000    5850
5.00000    2187
3.00000     148
Name: opinion_h1n1_sick_from_vacc, dtype: int64
4.00000    11629
5.00000     9973
2.00000     2206
1.00000     1221
3.00000     1216
Name: opinion_seas_vacc_effective, dtype: int64
2.00000    8954
4.00000    7630
1.00000    5974
5.00000    2958
3.00000     677
Name: opinion_seas_risk, dtype: int64
1.00000    11870
2.00000     7633
4.00000     4852
5.00000     1721
3.00000       94
Name: opinion_seas_sick_from_vacc, dtype: int64
65+ Years        6843
55 - 64 Years    5563
45 - 54 Years    5238
18 - 34 Years    5215
35 - 44 Years    3848
Name: age_group, dtype: int64
College Graduate    10097
Some College         7043
12 Years             5797
< 12 Years           2363
Name: education, dtype: int64
White                21222
Black                 2118
Hispanic              1755
Other or Multiple     1612
Name: race, dtype: int64
Female    15858
Male      10849
Name: sex, dtype: int64
<= $75,000, Above Poverty    12777
> $75,000                     6810
Below Poverty                 2697
Name: income_poverty, dtype: int64
Married        13555
Not Married    11744
Name: marital_status, dtype: int64
Own     18736
Rent     5929
Name: rent_or_own, dtype: int64
Employed              13560
Not in Labor Force    10231
Unemployed             1453
Name: employment_status, dtype: int64
lzgpxyit    4297
fpwskwrf    3265
qufhixun    3102
oxchjgsf    2859
kbazzjca    2858
bhuqouqj    2846
mlyzmhmf    2243
lrircsnp    2078
atmpeygn    2033
dqpwygqj    1126
Name: hhs_geo_region, dtype: int64
MSA, Not Principle  City    11645
MSA, Principle City          7864
Non-MSA                      7198
Name: census_msa, dtype: int64
1.00000    14474
0.00000     8056
2.00000     2803
3.00000     1125
Name: household_adults, dtype: int64
0.00000    18672
1.00000     3175
2.00000     2864
3.00000     1747
Name: household_children, dtype: int64
fcxhlnwr    2468
wxleyezf    1804
ldnlellj    1231
pxcmvdjn    1037
atmlpfrs     926
arjwrbjb     871
xicduogh     851
mfikgejo     614
vjjrobsf     527
rucpziij     523
xqicxuve     511
saaquncn     338
cfqqtusy     325
nduyfdeo     286
mcubkhph     275
wlfvacwt     215
dotnnunm     201
haxffmxo     148
msuufmds     124
phxvnwax      89
qnlwzans      13
Name: employment_industry, dtype: int64
xtkaffoo    1778
mxkfnird    1509
emcorrxb    1270
cmhcxjea    1247
xgwztkwe    1082
hfxkjkmi     766
qxajmpny     548
xqwwgdyp     485
kldqjyjy     469
uqqtjvyb     452
tfqavkke     388
ukymxvdu     372
vlluhbov     354
oijqvulv     344
ccgxvspp     341
bxpfxfdn     331
haliazsg     296
rcertsgn     276
xzmlyyjv     248
dlvbwzss     227
hodpvpew     208
dcjcmpih     148
pvmttkik      98
Name: employment_occupation, dtype: int64